version: '3.8'

services:
  web:
    build: .
    container_name: django-weather-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3

    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
