# Generated by Django 5.1.6 on 2025-03-05 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True)),
                ('temprature', models.FloatField()),
                ('forecast_Data', models.JSONField(blank=True, null=True)),
                ('latest_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
